on: push
name: Binary
jobs:     
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      - shell: bash
        run: |        
          git clean -dxf
          pim_mspr3_package.sh
