on:
  pull_request:
    types: [closed]
name: Deploy
jobs:     
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy_on_server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp://51.91.148.161.fr
          username: ducobu
          password: ducobu          
